"""Read-only inventory of the original xRC Unity scenes.

This intentionally emits metadata only.  It never edits the xRC install and it
does not consume artifacts generated by earlier experiments.
"""
from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from pathlib import Path
from typing import Any

import UnityPy


KEYWORDS = (
    "rebuilt",
    "hub",
    "ramp",
    "trench",
    "tower",
    "net",
    "fuel",
    "ball",
    "legacy",
    "legacy robot",
    "robot",
    "goal",
    "outtake",
    "return",
    "score",
)


def ptr_id(value: Any) -> int | None:
    return getattr(value, "path_id", None) or getattr(value, "m_PathID", None)


def inspect_level(path: Path) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    env = UnityPy.load(str(path))
    objects = {obj.path_id: obj for obj in env.objects}
    types = {obj.path_id: obj.type.name for obj in env.objects}
    game_objects: dict[int, Any] = {}
    transforms: dict[int, Any] = {}
    transform_to_go: dict[int, int] = {}
    go_to_transform: dict[int, int] = {}

    for obj in env.objects:
        try:
            if obj.type.name == "GameObject":
                game_objects[obj.path_id] = obj.read()
            elif obj.type.name == "Transform":
                transform = obj.read()
                transforms[obj.path_id] = transform
                go_id = ptr_id(transform.m_GameObject)
                if go_id is not None:
                    transform_to_go[obj.path_id] = go_id
                    go_to_transform[go_id] = obj.path_id
        except Exception:
            continue

    def go_name(go_id: int | None) -> str:
        go = game_objects.get(go_id)
        return str(getattr(go, "m_Name", "?")) if go is not None else "?"

    def hierarchy_path(transform_id: int) -> str:
        parts: list[str] = []
        seen: set[int] = set()
        current: int | None = transform_id
        while current in transforms and current not in seen:
            seen.add(current)
            parts.append(go_name(transform_to_go.get(current)))
            current = ptr_id(transforms[current].m_Father)
        return "/".join(reversed(parts))

    rows: list[dict[str, Any]] = []
    for go_id, go in game_objects.items():
        component_types: list[str] = []
        component_ids: list[int] = []
        for component in getattr(go, "m_Component", []) or []:
            pointer = getattr(component, "component", component)
            component_id = ptr_id(pointer)
            if component_id is not None:
                component_ids.append(component_id)
                component_types.append(types.get(component_id, "Unknown"))
        transform_id = go_to_transform.get(go_id)
        name = go_name(go_id)
        full_path = hierarchy_path(transform_id) if transform_id else name
        rows.append(
            {
                "level": path.name,
                "game_object_id": go_id,
                "transform_id": transform_id,
                "name": name,
                "path": full_path,
                "active_self": bool(getattr(go, "m_IsActive", True)),
                "layer": int(getattr(go, "m_Layer", 0)),
                "components": component_types,
                "component_ids": component_ids,
                "keyword_match": any(word in full_path.lower() for word in KEYWORDS),
            }
        )

    summary = {
        "level": path.name,
        "object_count": len(env.objects),
        "game_object_count": len(rows),
        "type_counts": dict(Counter(obj.type.name for obj in env.objects)),
        "root_names": sorted(
            row["name"]
            for row in rows
            if row["transform_id"] in transforms
            and ptr_id(transforms[row["transform_id"]].m_Father) not in transforms
        ),
        "keyword_paths": sorted(row["path"] for row in rows if row["keyword_match"]),
    }
    return rows, summary


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--levels", nargs="+", default=["level74", "level75", "level76"])
    args = parser.parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    all_rows: list[dict[str, Any]] = []
    summaries: list[dict[str, Any]] = []
    for level_name in args.levels:
        rows, summary = inspect_level(args.data_dir / level_name)
        all_rows.extend(rows)
        summaries.append(summary)

    with (args.out_dir / "scene_hierarchy.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(all_rows[0]))
        writer.writeheader()
        for row in all_rows:
            writer.writerow({**row, "components": ";".join(row["components"]), "component_ids": ";".join(map(str, row["component_ids"]))})
    (args.out_dir / "scene_inventory.json").write_text(
        json.dumps(summaries, indent=2), encoding="utf-8"
    )
    print(json.dumps(summaries, indent=2))


if __name__ == "__main__":
    main()
